### ISSUE TITLE
Failed to build on both stable and nightly

### ISSUE THREAD

**Issue by amosbird** [dwrensha/capnproto-rust#52]
I'm getting this error:

```
failed to run custom build command for `capnp-rpc v0.5.0`
Process didn't exit successfully: `/opt/capnp-raft/target/debug/build/capnp-rpc-1baa9a0f1ce31119/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:365
stack backtrace:
   1:     0x7fb138e90620 - sys::backtrace::tracing::imp::write::he9cf93dccfa17cceNlt
   2:     0x7fb138e931e5 - panicking::log_panic::closure.39173
   3:     0x7fb138e92c31 - panicking::log_panic::hd9f4aa0cbdff587aZlx
   4:     0x7fb138e79f93 - sys_common::unwind::begin_unwind_inner::h90fc1a96c34cff35eds
   5:     0x7fb138e7a608 - sys_common::unwind::begin_unwind_fmt::hfca8a38c37457f6fkcs
   6:     0x7fb138e8fcf1 - rust_begin_unwind
   7:     0x7fb138ec06bf - panicking::panic_fmt::h19598b35d555b127wZK
   8:     0x7fb138ebc7d8 - panicking::panic::hfefb33ce32c56da43XK
   9:     0x7fb138de0f35 - option::Option<T>::unwrap::h1607710876796834354
                        at ../src/libcore/macros.rs:20
  10:     0x7fb138dde1c0 - main::h7000649270783f3cfaa
                        at /root/.cargo/registry/src/github.com-0a35038f75765ae4/capnp-rpc-0.5.0/build.rs:11
  11:     0x7fb138e92974 - sys_common::unwind::try::try_fn::h6140512138114007296
  12:     0x7fb138e8fb58 - __rust_try
  13:     0x7fb138e9260f - rt::lang_start::h21dafd243738f0d57ix
  14:     0x7fb138deffe9 - main
  15:     0x7fb137fcdaf4 - __libc_start_main
  16:     0x7fb138ddde78 - <unknown>
  17:                0x0 - <unknown>
```

I've tested both stable and nightly, on Windows and Linux.

**Comment by dwrensha** [comment]
Do you have the `capnp` tool installed on your system? https://capnproto.org/install.html

**Comment by amosbird** [comment]
Oh. I don't know that is a prerequisite. On Windows there are path issues.
```
--- stderr
capnp compile: /c/Users/amosb\include/capnp\rpc.capnp: no such file
```
